#!/usr/bin/env python3
"""
MedBot Clinic Management - Quick Setup Script
Helps users configure the application interactively
"""

import os
import secrets
import sys
from pathlib import Path

def print_header(text):
    """Print a formatted header"""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")

def print_step(number, text):
    """Print a step number and description"""
    print(f"\n📋 Step {number}: {text}")
    print("-" * 60)

def get_input(prompt, default=None, required=True):
    """Get user input with optional default"""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    while True:
        value = input(prompt).strip()
        
        if value:
            return value
        elif default:
            return default
        elif not required:
            return ""
        else:
            print("⚠️  This field is required. Please enter a value.")

def generate_secret_key():
    """Generate a secure random secret key"""
    return secrets.token_hex(32)

def check_python_version():
    """Check if Python version is compatible"""
    if sys.version_info < (3, 9):
        print("❌ Python 3.9 or higher is required!")
        print(f"   Current version: {sys.version}")
        sys.exit(1)
    print(f"✅ Python version: {sys.version.split()[0]}")

def create_env_file():
    """Create .env file with user input"""
    print_header("MedBot Clinic Management - Quick Setup")
    print("This script will help you configure the application.")
    print("Press Ctrl+C at any time to cancel.")
    
    # Check if .env already exists
    if os.path.exists('.env'):
        overwrite = input("\n⚠️  .env file already exists. Overwrite? (y/N): ")
        if overwrite.lower() != 'y':
            print("Setup cancelled.")
            sys.exit(0)
    
    config = {}
    
    # Step 1: Flask Configuration
    print_step(1, "Flask Configuration")
    config['FLASK_SECRET_KEY'] = generate_secret_key()
    print(f"✅ Generated secure secret key: {config['FLASK_SECRET_KEY'][:16]}...")
    
    # Step 2: Gmail Configuration
    print_step(2, "Gmail Configuration (Required for Email Notifications)")
    print("\nℹ️  You need a Gmail App Password. Here's how:")
    print("   1. Go to https://myaccount.google.com/")
    print("   2. Security → 2-Step Verification (enable it)")
    print("   3. Security → App passwords → Generate for 'Mail'")
    print("   4. Copy the 16-character password\n")
    
    config['MAIL_USERNAME'] = get_input("Gmail address (e.g., clinic@gmail.com)")
    config['MAIL_PASSWORD'] = get_input("Gmail App Password (16 characters)")
    
    # Step 3: Flowise Configuration
    print_step(3, "Flowise AI Configuration (Optional)")
    print("\nℹ️  Flowise provides AI chatbot capabilities.")
    print("   Leave empty to skip (chatbot will use basic pattern matching)\n")
    
    use_flowise = get_input("Do you want to configure Flowise? (y/N)", "n", False)
    
    if use_flowise.lower() == 'y':
        config['FLOWISE_URL'] = get_input(
            "Flowise Prediction URL",
            "http://localhost:3000/api/v1/prediction/YOUR-FLOW-ID",
            False
        )
        config['FLOWISE_API_KEY'] = get_input("Flowise API Key (optional)", "", False)
    else:
        config['FLOWISE_URL'] = ""
        config['FLOWISE_API_KEY'] = ""
    
    # Step 4: Doctor Credentials
    print_step(4, "Default Doctor Account")
    print("\nℹ️  This creates the initial doctor account.")
    print("   You can change these later in the database\n")
    
    config['DEFAULT_DOCTOR_USERNAME'] = get_input("Doctor username", "doctor")
    config['DEFAULT_DOCTOR_PASSWORD'] = get_input("Doctor password", "doctor123")
    config['DEFAULT_DOCTOR_EMAIL'] = get_input(
        "Doctor email",
        "doctor@medbotclinic.com"
    )
    
    # Step 5: Working Hours
    print_step(5, "Clinic Working Hours")
    config['CLINIC_START_TIME'] = get_input("Clinic opens at", "09:00")
    config['CLINIC_END_TIME'] = get_input("Clinic closes at", "18:00")
    config['CLINIC_LUNCH_START'] = get_input("Lunch break starts at", "13:00")
    config['CLINIC_LUNCH_END'] = get_input("Lunch break ends at", "14:00")
    config['SLOT_INTERVAL_MINUTES'] = get_input("Appointment slot interval (minutes)", "15")
    
    # Create .env file
    print_step(6, "Creating .env File")
    
    env_content = f"""# MedBot Clinic Management - Configuration
# Generated by setup script

# Flask Configuration
FLASK_SECRET_KEY={config['FLASK_SECRET_KEY']}

# Gmail Configuration
MAIL_USERNAME={config['MAIL_USERNAME']}
MAIL_PASSWORD={config['MAIL_PASSWORD']}

# Flowise Configuration
FLOWISE_URL={config['FLOWISE_URL']}
FLOWISE_API_KEY={config['FLOWISE_API_KEY']}
FLOWISE_TIMEOUT=12
DEBUG_FLOWISE=True

# Database
DATABASE_URI=sqlite:///clinic.db

# Application Settings
DEBUG=True
PORT=5000
HOST=127.0.0.1

# Clinic Configuration
CLINIC_START_TIME={config['CLINIC_START_TIME']}
CLINIC_END_TIME={config['CLINIC_END_TIME']}
CLINIC_LUNCH_START={config['CLINIC_LUNCH_START']}
CLINIC_LUNCH_END={config['CLINIC_LUNCH_END']}
SLOT_INTERVAL_MINUTES={config['SLOT_INTERVAL_MINUTES']}

# Doctor Default Credentials
DEFAULT_DOCTOR_USERNAME={config['DEFAULT_DOCTOR_USERNAME']}
DEFAULT_DOCTOR_PASSWORD={config['DEFAULT_DOCTOR_PASSWORD']}
DEFAULT_DOCTOR_EMAIL={config['DEFAULT_DOCTOR_EMAIL']}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("✅ .env file created successfully!")
    
    # Summary
    print_header("Setup Complete!")
    print("✅ Configuration file created: .env")
    print("✅ Flask secret key generated")
    print("✅ Gmail configured" if config['MAIL_USERNAME'] else "⚠️  Gmail not configured")
    print("✅ Flowise configured" if config['FLOWISE_URL'] else "ℹ️  Flowise skipped (optional)")
    print("✅ Clinic hours configured")
    
    print("\n🚀 Next Steps:")
    print("   1. Install dependencies: pip install -r requirements.txt")
    print("   2. Run the application: python app.py")
    print("   3. Open browser: http://localhost:5000")
    print("   4. Login as doctor:")
    print(f"      Username: {config['DEFAULT_DOCTOR_USERNAME']}")
    print(f"      Password: {config['DEFAULT_DOCTOR_PASSWORD']}")
    
    print("\n⚠️  Security Reminder:")
    print("   - Change doctor password after first login")
    print("   - Never commit .env file to git")
    print("   - Keep your Gmail App Password secure")
    
    print("\n📖 For more information, see README.md")
    print("\n" + "=" * 60 + "\n")

def install_dependencies():
    """Install Python dependencies"""
    print_step("Optional", "Install Dependencies")
    install = get_input("Install Python dependencies now? (y/N)", "n", False)
    
    if install.lower() == 'y':
        print("\n📦 Installing dependencies...")
        os.system("pip install -r requirements.txt")
        print("✅ Dependencies installed!")

if __name__ == "__main__":
    try:
        check_python_version()
        create_env_file()
        install_dependencies()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error during setup: {e}")
        sys.exit(1)